services:
  - type: web
    name: to-do-app
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATA_DIR
        value: /var/data
    disk:
      name: to-do-data
      mountPath: /var/data
      sizeGB: 1
